default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: s6xapi_development
test:
  <<: *default
  database: s6xapi_test
production:
  <<: *default
  database: s6xapi_production
  username: s6xapi
  password: <%= ENV['S6XAPI_DATABASE_PASSWORD'] %>
